use evchart_data_v3;

INSERT INTO network_providers (np_uuid, np_key, np_label, is_active)
VALUES
(UUID(), "7charge", "7Charge", 1),
(UUID(),  "abm", "ABM", 1),
(UUID(),  "addenergie", "AddÉnergie", 1),
(UUID(),  "ampedup", "AmpedUp! Networks", 1),
(UUID(), "ampup", "AmpUp", 1),
(UUID(), "applegreen_electric", "applegreen electric", 1),
(UUID(), "autel", "autel", 1),
(UUID(), "bc_hydro", "BC Hydro", 1),
(UUID(), "beta_technologies", "Beta Technologies", 1),
(UUID(), "blink", "Blink", 1),
(UUID(), "bp_pulse", "bp pulse", 1),
(UUID(), "chargelab", "ChargeLab", 1),
(UUID(), "chargenet", "ChargeNet", 1),
(UUID(), "chargepoint", "ChargePoint", 1),
(UUID(), "chargesmart_ev", "ChargeSmart EV", 1),
(UUID(), "chargeup", "ChargeUP", 1),
(UUID(), "chargie", "Chargie", 1),
(UUID(), "circlek", "CircleK Charge", 1),
(UUID(), "circlek_couche_tard_recharge", "CircleK/Couche-Tard Recharge", 1),
(UUID(), "circuit_electrique", "Circuit électrique", 1),
(UUID(), "echarge", "eCharge Network", 1),
(UUID(), "electrify_america", "Electrify America", 1),
(UUID(), "electrify_canada", "Electrify Canada", 1),
(UUID(), "enel_x_way", "Enel X Way", 1),
(UUID(),  "envirospark", "EnviroSpark", 1),
(UUID(), "evbolt", "EVBOLT", 1),
(UUID(), "ev_connect", "EV Connect", 1),
(UUID(), "evcs", "EVCS", 1),
(UUID(), "evgateway", "evGateway", 1),
(UUID(), "evgo", "EVgo", 1),
(UUID(), "evmatch", "EVmatch", 1),
(UUID(), "evpower", "eVPower", 1),
(UUID(), "ev_range", "EV Range", 1),
(UUID(), "flash", "FLASH", 1),
(UUID(), "flo", "FLO", 1),
(UUID(), "foresta", "Foresta", 1),
(UUID(), "fpl_evolution", "FPL EVolution", 1),
(UUID(), "francis_energy", "Francis Energy", 1),
(UUID(), "graviti_energy", "Graviti Energy", 1),
(UUID(), "gravity_charging_center", "Gravity Charging Center", 1),
(UUID(), "honeybadger_charging", "HoneyBadger Charging", 1),
(UUID(), "hwisel", "Hwisel", 1),
(UUID(), "incharge", "InCharge", 1),
(UUID(), "ivy", "Ivy", 1),
(UUID(), "jule", "Jule", 1),
(UUID(), "kwik_trip", "Kwik Trip", 1),
(UUID(), "livingston_energy_group", "Livingston Energy Group", 1),
(UUID(), "loop", "Loop", 1),
(UUID(), "matcha_electric", "Matcha Electric", 1),
(UUID(), "non_networked", "Non-Networked", 1),
(UUID(), "noodoe", "Noodoe", 1),
(UUID(), "on_the_run_ev", "On the Run EV", 1),
(UUID(), "opconnect", "OpConnect", 1),
(UUID(), "petro_canada", "Petro-Canada", 1),
(UUID(), "powerflex", "PowerFlex", 1),
(UUID(), "powernode", "PowerNode", 1),
(UUID(), "powerport_evc", "PowerPort EVC", 1),
(UUID(), "powerpump", "PowerPump", 1),
(UUID(), "red_e_charging", "Red E Charging", 1),
(UUID(), "revel", "Revel", 1),
(UUID(), "revitalize_charging_solutions", "Revitalize Charging Solutions", 1),
(UUID(), "rivian_adventure", "Rivian Adventure Network", 1),
(UUID(), "rivian_waypoints", "Rivian Waypoints", 1),
(UUID(), "shell_recharge", "Shell Recharge", 1),
(UUID(), "stay_n_charge", "Stay-N-Charge", 1),
(UUID(), "sun_country_highway", "Sun Country Highway", 1),
(UUID(), "swtch_energy", "SWTCH Energy", 1),
(UUID(), "tesla_destination", "Tesla Destination", 1),
(UUID(), "tesla_supercharger", "Tesla Supercharger", 1),
(UUID(), "turnongreen", "TurnOnGreen", 1),
(UUID(), "universal_ev_chargers", "Universal EV Chargers", 1),
(UUID(), "volta", "Volta", 1),
(UUID(), "wattev", "WattEV", 1),
(UUID(), "wave", "WAVE", 1),
(UUID(), "zef", "ZEF Network", 1)