type Mapping = {
  [key: string]: string;
};

export const projectTypeMapping = (key: string): string | undefined => {
  const mapping: Mapping = {
    new_station: "Install a New Station",
    existing_station: "Update an Existing Station",
    o_and_m: "Only provide operation and maintenance",
  };
  return mapping[key];
};

export const statesMapping = (key: string): string | undefined => {
  const mapping: Mapping = {
    alabama: "AL",
    alaska: "AK",
    arizona: "AZ",
    arkansas: "AR",
    california: "CA",
    colorado: "CO",
    connecticut: "CT",
    delaware: "DE",
    DC: "DC",
    florida: "FL",
    georgia: "GA",
    hawaii: "HI",
    idaho: "ID",
    illinois: "IL",
    indiana: "IN",
    iowa: "IA",
    kansas: "KS",
    kentucky: "KY",
    louisiana: "LA",
    maine: "ME",
    maryland: "MD",
    massachusetts: "MA",
    michigan: "MI",
    minnesota: "MN",
    mississippi: "MS",
    missouri: "MO",
    montana: "MT",
    nebraska: "NE",
    nevada: "NV",
    newHampshire: "NH",
    newJersey: "NJ",
    newMexico: "NM",
    newYork: "NY",
    northCarolina: "NC",
    northDakota: "ND",
    ohio: "OH",
    oklahoma: "OK",
    oregon: "OR",
    pennsylvania: "PA",
    rhodeIsland: "RI",
    southCarolina: "SC",
    southDakota: "SD",
    tennessee: "TN",
    texas: "TX",
    utah: "UT",
    vermont: "VT",
    virginia: "VA",
    washington: "WA",
    westVirginia: "WV",
    wisconsin: "WY",
    wyoming: "WY",
    americanSamoa: "AS",
    guam: "GU",
    northernMarianaIslands: "MP",
    puertoRico: "PR",
    usMinorOutlyingIslands: "UM",
    usVirginIslands: "VI",
  };
  return mapping[key];
};

export const stateDropdownMapping = (key: string): string | undefined => {
  const mapping: Mapping = {
    al: "AL",
    ak: "AK",
    az: "AZ",
    ar: "AR",
    ca: "CA",
    co: "CO",
    ct: "CT",
    de: "DE",
    dc: "DC",
    fl: "FL",
    ga: "GA",
    hi: "HI",
    id: "ID",
    il: "IL",
    in: "IN",
    ia: "IA",
    ks: "KS",
    ky: "KY",
    la: "LA",
    me: "ME",
    md: "MD",
    ma: "MA",
    mi: "MI",
    mn: "MN",
    ms: "MS",
    mo: "MO",
    mt: "MT",
    ne: "NE",
    nv: "NV",
    nh: "NN",
    nj: "NJ",
    nm: "NM",
    ny: "NY",
    nc: "NC",
    nd: "ND",
    oh: "OH",
    ok: "OK",
    or: "OR",
    pa: "PA",
    ri: "RI",
    sc: "SC",
    sd: "SD",
    tn: "TN",
    tx: "TX",
    ut: "UT",
    vt: "VT",
    va: "VA",
    wa: "WA",
    wv: "WV",
    wi: "WI",
    wy: "WY",
    as: "AS",
    gu: "GU",
    mp: "MP",
    pr: "PR",
    um: "UM",
    vi: "VI",
  };
  return mapping[key];
};

export const stateCodeMapping = (key: string): string | undefined => {
  const mapping: Mapping = {
    al: "Alabama",
    ak: "Alaska",
    az: "Arizona",
    ar: "Arkansas",
    ca: "California",
    co: "Colorado",
    ct: "Connecticut",
    de: "Delaware",
    dc: "DC",
    fl: "Florida",
    ga: "Georgia",
    hi: "Hawaii",
    id: "Idaho",
    il: "Illinois",
    in: "Indiana",
    ia: "Iowa",
    ks: "Kansas",
    ky: "Kentucky",
    la: "Louisiana",
    me: "Maine",
    md: "Maryland",
    ma: "Massachusetts",
    mi: "Michigan",
    mn: "Minnesota",
    ms: "Mississippi",
    mo: "Missouri",
    mt: "Montana",
    ne: "Nebraska",
    nv: "Nevada",
    nh: "New Hampshire",
    nj: "New Jersey",
    nm: "New Mexico",
    ny: "New York",
    nc: "North Carolina",
    nd: "North Dakota",
    oh: "Ohio",
    ok: "Oklahoma",
    or: "Oregon",
    pa: "Pennsylvania",
    ri: "Rhode Island",
    sc: "South Carolina",
    sd: "South Dakota",
    tn: "Tennessee",
    tx: "Texas",
    ut: "Utah",
    vt: "Vermont",
    va: "Virginia",
    wa: "Washington",
    wv: "West Virginia",
    wi: "Wisconsin",
    wy: "Wyoming",
    as: "American Samoa",
    gu: "Guam",
    mp: "Northern Mariana Islands",
    pr: "Puerto Rico",
    um: "US Minor Outlying Islands",
    vi: "US Virgin Islands",
  };
  return mapping[key];
};
