AWSTemplateFormatVersion: 2010-09-09
Description: ""

Metadata: {}

Parameters:
  LambdaFunctionDescription:
    Type: String
    #Description:

  LambdaFunctionFunctionName:
    Type: String
    #Description:

  LambdaFunctionLayerArns:
    Type: CommaDelimitedList
    Default: ""
    #Description:

  RepositoryName:
    Type: String
    Default: ""
    Description: ECR repository name

  TagName:
    Type: String
    Default: latest
    Description: ECR tag

  LambdaFunctionLogsLogGroupRetentionInDays:
    Type: Number
    AllowedValues:
      - 1
      - 3
      - 5
      - 7
      - 14
      - 30
      - 60
      - 90
      - 120
      - 150
      - 180
      - 365
      - 400
      - 545
      - 731
      - 1096
      - 1827
      - 2192
      - 2557
      - 2922
      - 3288
      - 3653
    Default: 30
    #Description:

  LambdaFunctionMemorySize:
    Type: Number
    Default: 1024
    #Description:
    MaxValue: 10240
    MinValue: 128

  LambdaFunctionNetworkProxy:
    Type: String
    Default: ""
    #Description:

  LambdaFunctionNetworkProxyCert:
    Type: String
    Default: ""
    #Description:

  LambdaFunctionRuntime:
    Type: String
    Default: python3.11
    #Description:

  LambdaFunctionTimeout:
    Type: Number
    Default: 30
    #Description:

  LambdaFunctionVpcConfigSecurityGroupId:
    Type: String
    #Description:

  LambdaFunctionVpcConfigSubnetIds:
    Type: CommaDelimitedList
    #Description:

  LambdaResourceCommitId:
    Type: String
    #Description:

  SubEnvironment:
    Type: String
    Default: ""
    #Description:

Mappings:
  EnvironmentMap:
    "414275662771":
      Environment: dev
    "030628784534":
      Environment: test
    "888515010394":
      Environment: prod

  LambdaExecutionRoleName:
    dev:
      Name: role/LambdaExecution-NeviDev
    test:
      Name: role/LambdaExecution-NeviTest
    prod:
      Name: role/LambdaExecution-NeviProd

Conditions:
  isNotSubEnvironment: !Equals [ !Ref SubEnvironment, "" ]
  useLayers: !Not [ !Equals [ !Join [ ",", !Ref LambdaFunctionLayerArns ], "" ] ]
  usesS3: !Equals [!Ref RepositoryName, ""]
  usesECR: !Not [ !Equals [!Ref RepositoryName, ""]]

Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Condition: usesS3
    Metadata:
      guard:
        SuppressedRules:
          - LAMBDA_DLQ_CHECK
          - LAMBDA_CONCURRENCY_CHECK
        SuppressedRulesDescription:
          LAMBDA_DLQ_CHECK: >
            Not required as all application Lambdas are synchronous.
          LAMBDA_CONCURRENCY_CHECK: >
            Not required as application traffic is limited in intensity and sporadic; limiting
            concurrency has more potential to cause issues than resolve them in this case.
    Properties:
      Code:
        S3Bucket: !Sub
          - ev-chart-artifact-${Environment}-${AWS::Region}
          -
            Environment: !If
              - isNotSubEnvironment
              - !FindInMap [ EnvironmentMap, !Ref AWS::AccountId, Environment ]
              - !Ref SubEnvironment
        S3Key: !Sub deploy/lambda/${LambdaResourceCommitId}/${LambdaFunctionFunctionName}.zip
      Description: !Ref LambdaFunctionDescription
      Environment:
        Variables:
          ENVIRONMENT: !FindInMap [ EnvironmentMap, !Ref AWS::AccountId, Environment ]
          NETWORKPROXY: !Ref LambdaFunctionNetworkProxy
          NETWORKPROXYCERT: !Ref LambdaFunctionNetworkProxyCert
          SUBENVIRONMENT: !If
            - isNotSubEnvironment
            - ""
            - !Ref SubEnvironment
      FunctionName: !Sub
        - EV-ChART_${LambdaFunctionFunctionName}${SubEnvironmentName}
        -
          SubEnvironmentName: !If
            - isNotSubEnvironment
            - ""
            - !Sub _${SubEnvironment}
      Handler: index.handler
      KmsKeyArn: "{{resolve:ssm:/ev-chart/kms/general-arn}}"
      Layers: !If
        - useLayers
        - !Ref LambdaFunctionLayerArns
        - !Ref AWS::NoValue
      MemorySize: !Ref LambdaFunctionMemorySize
      PackageType: Zip
      Role: !Sub
        - "arn:${AWS::Partition}:iam::${AWS::AccountId}:${RoleName}"
        -
          RoleName: !FindInMap
            - LambdaExecutionRoleName
            - !FindInMap [ EnvironmentMap, !Ref AWS::AccountId, Environment ]
            - Name
      Runtime: !Ref LambdaFunctionRuntime
      #Tags:
      Timeout: !Ref LambdaFunctionTimeout
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaFunctionVpcConfigSecurityGroupId
        SubnetIds: !Ref LambdaFunctionVpcConfigSubnetIds

  LambdaECRFunction:
    Type: AWS::Lambda::Function
    Condition: usesECR
    Metadata:
      guard:
        SuppressedRules:
          - LAMBDA_DLQ_CHECK
          - LAMBDA_CONCURRENCY_CHECK
        SuppressedRulesDescription:
          LAMBDA_DLQ_CHECK: >
            Not required as all application Lambdas are synchronous.
          LAMBDA_CONCURRENCY_CHECK: >
            Not required as application traffic is limited in intensity and sporadic; limiting
            concurrency has more potential to cause issues than resolve them in this case.
    Properties:
      Code:
        # Update to point to the correct paths
        ImageUri: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${RepositoryName}:${TagName}
        # ImageUri: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/ev-chart-lambdas/${RepositoryName}:${TagName}
        # ^ to use with pipeline deployed images
      PackageType: Image
      Description: !Ref LambdaFunctionDescription
      Environment:
        Variables:
          ENVIRONMENT: !FindInMap [ EnvironmentMap, !Ref AWS::AccountId, Environment ]
          NETWORKPROXY: !Ref LambdaFunctionNetworkProxy
          NETWORKPROXYCERT: !Ref LambdaFunctionNetworkProxyCert
          SUBENVIRONMENT: !If
            - isNotSubEnvironment
            - ""
            - !Ref SubEnvironment
      FunctionName: !Sub
      # for the name should I just use the ecr name as the function name?
        - EV-ChART_UI_Test_${LambdaFunctionFunctionName}${SubEnvironmentName}
        -
          SubEnvironmentName: !If
            - isNotSubEnvironment
            - ""
            - !Sub _${SubEnvironment}
      KmsKeyArn: "{{resolve:ssm:/ev-chart/kms/general-arn}}"
      MemorySize: !Ref LambdaFunctionMemorySize
      Role: !Sub
        - "arn:${AWS::Partition}:iam::${AWS::AccountId}:${RoleName}"
        -
          RoleName: !FindInMap
            - LambdaExecutionRoleName
            - !FindInMap [ EnvironmentMap, !Ref AWS::AccountId, Environment ]
            - Name
      #Tags:
      Timeout: !Ref LambdaFunctionTimeout
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaFunctionVpcConfigSecurityGroupId
        SubnetIds: !Ref LambdaFunctionVpcConfigSubnetIds

  LambdaFunctionLogsLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Metadata:
      guard:
        SuppressedRules:
          - CW_LOGGROUP_RETENTION_PERIOD_CHECK
        SuppressedRulesDescription:
          CW_LOGGROUP_RETENTION_PERIOD_CHECK: >
            False positive; this property is included as a parameter reference.
    Properties:
      KmsKeyId: !Sub arn:${AWS::Partition}:kms:${AWS::Region}:${AWS::AccountId}:alias/ev-chart/general
      LogGroupName: !If
        - usesS3
        - !Sub /aws/lambda/${LambdaFunction}
        - !Sub /aws/lambda/${LambdaECRFunction}
      RetentionInDays: !Ref LambdaFunctionLogsLogGroupRetentionInDays
      #Tags:

Outputs:
  LambdaFunctionArn:
    Description: The ARN for the EV-ChART example Lambda function.
    Value: !If
      - usesS3
      - !GetAtt LambdaFunction.Arn
      - !GetAtt LambdaECRFunction.Arn
